### ISSUE TITLE
Parse staticWorkers from Terraform json input

### ISSUE THREAD

**Issue by osery** [kubermatic/kubeone#1146]
**What feature would you like to be added?**

In order to be able to deploy and update a cluster with Terraform managed worker (static) nodes, it would be great to have these also parsed from the Terraform json input. E.g. when called as:

```shell
kubeone apply -t tf.json
```

with tf.json including:

```yaml
staticWorkers:
  hosts:
   - publicAddress: 'X.Y.Z.W'
     hostname: 'worker0'
     sshUsername: ubuntu
     sshPrivateKeyFile: ssh-key
     sshPort: 22
```

**What are use cases of the feature?**

As above.

Many thanks for considering.
