### ISSUE TITLE
Missing etcd pod on fresh cluster

### ISSUE THREAD

**Issue by shibumi** [kubermatic/kubeone#1247]
**What happened**:

I somehow crashed our Staging Cluster, so I played a lot around with it (removing a node.. adding a node.. etc).
After all I couldn't fix it, hence I decided to just reset the whole cluster and re-apply the manifest.yaml

The cluster consists of three control and three worker nodes, but I see only 2 etcd pods in the kube-system namespace.
I had the same problem before resetting the cluster. Now after resetting and re-applying the manifest.yaml it still persists.
I got a fresh k8s cluster with three control nodes, but with just two etcd pods.

**What is the expected behavior**:

KubeOne should spawn one etcd pod per cluster node for a good quorum between the etcd pods.

**How to reproduce the issue**:

Not sure if it's really easy reproducible or just me:

* Build a cluster based on Flatcar containers in an ESXI environment
* On an additional node install a haproxy loadbalancer as kubeapi loadbalancer
* Apply my manifest.yaml
* Reset the whole cluster
* Re-Apply the manifest.yaml on the "refreshed" nodes.

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): 
```json
{
  "kubeone": {
    "major": "1",
    "minor": "1",
    "gitVersion": "v1.1.0",
    "gitCommit": "3e84d523a75cd178a7801a0fccf2b3195db3a376",
    "gitTreeState": "",
    "buildDate": "2021-01-05T10:29:35+00:00",
    "goVersion": "go1.15.6",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "19",
    "gitVersion": "v1.19.0",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```
Operating system: Arch Linux (client), Flatcar OS (Servers)
Provider you're deploying cluster on: Vsphere (but I am not using the vsphere API, just static Workers)
Operating system you're deploying on: Flatcar OS

My manifest.yaml:
```yaml
apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
name: ob-stage
versions:
  kubernetes: "1.18.2"
clusterNetwork:
  podSubnet: ""
  serviceSubnet: ""
  serviceDomainName: ""
  nodePortRange: ""
  cni:
    canal:
      mtu: 1450
cloudProvider:
  none: {}
features:
  podNodeSelector:
    enable: false
    config:
      configFilePath: ""
  podSecurityPolicy:
    enable: false
  podPresets:
    enable: false
  staticAuditLog:
    enable: false
    config:
      policyFilePath: ""
      logPath: "/var/log/kubernetes/audit.log"
      logMaxAge: 30
      logMaxBackup: 3
      logMaxSize: 100
  dynamicAuditLog:
    enable: false
  metricsServer:
    enable: true
  openidConnect:
    enable: false
    config:
      issuerUrl: ""
      clientId: "kubernetes"
      usernameClaim: "sub"
      usernamePrefix: "oidc:"
      groupsClaim: "groups"
      groupsPrefix: "oidc:"
      signingAlgs: "RS256"
      requiredClaim: ""
      caFile: ""
systemPackages:
  configureRepositories: true # it's true by default
addons:
  enable: false
  path: "./addons"
controlPlane:
  hosts:
  - publicAddress: '10.88.10.2'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
    taints:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
  - publicAddress: '10.88.10.3'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
    taints:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
  - publicAddress: '10.88.10.4'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
    taints:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
staticWorkers:
  hosts:
  - publicAddress: '10.88.10.11'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
  - publicAddress: '10.88.10.12'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
  - publicAddress: '10.88.10.13'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
apiEndpoint:
  host: '10.88.10.10'
  port: 6443
machineController:
  deploy: false
```
