### ISSUE TITLE
Amazon Linux2 is missing crictl to run KubeOne installation of Controlplane

### ISSUE THREAD

**Issue by mfahlandt** [kubermatic/kubeone#1281]
**What happened**:

If i want to use Amazon_Linux2 as OS on the CP, it is showing the error that crictl is missing.

If you use Docker as runtime the error appears 

```
NFO[14:09:59 CET] Restarting unhealthy API servers if needed...
[172.31.138.126] sudo: crictl: command not found
WARN[14:09:59 CET] Task failed, error was: Process exited with status 1
```

If you use containerd as runtime the error is:

```
[172.31.221.32] [preflight] Some fatal errors occurred:
[172.31.221.32]         [ERROR FileExisting-crictl]: crictl not found in system path
[172.31.221.32] [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

```

**What is the expected behavior**:

The CP comes up on Amazon_Linux2 and a restart of the API Servers is possible

**How to reproduce the issue**:

Create a Setup using Amazon_Linux2 as os.

**Anything else we need to know?**

It works in v1.2.0-alpha.0 of KubeOne

KubeOne YAML

```
apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
versions:
  kubernetes: "v1.19.6-eks-1-19-1"
containerRuntime:
  containerd: {}
cloudProvider:
  aws: {}
assetConfiguration:
  kubernetes:
    imageRepository: "public.ecr.aws/eks-distro/kubernetes"
  pause:
    imageRepository: "public.ecr.aws/eks-distro/kubernetes"
    imageTag: "v1.19.6-eks-1-19-1"
  etcd:
    imageRepository: "public.ecr.aws/eks-distro/etcd-io"
    imageTag: "v3.4.14-eks-1-19-1"
  coreDNS:
    imageRepository: "public.ecr.aws/eks-distro/coredns"
    imageTag: "v1.8.0-eks-1-19-1"
  metricsServer:
    imageRepository: "public.ecr.aws/eks-distro/kubernetes-sigs"
    imageTag: "v0.4.0-eks-1-19-1"
  cni:
    url: "https://distro.eks.amazonaws.com/kubernetes-1-19/releases/1/artifacts/plugins/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tar.gz"
  nodeBinaries:
    url: "https://distro.eks.amazonaws.com/kubernetes-1-19/releases/1/artifacts/kubernetes/v1.19.6/kubernetes-node-linux-amd64.tar.gz"
  kubectl:
    url: "https://distro.eks.amazonaws.com/kubernetes-1-19/releases/1/artifacts/kubernetes/v1.19.6/bin/linux/amd64/kubectl"
```

**Information about the environment**:
KubeOne version (`kubeone version`): 1.2.0
Operating system: Ubuntu 20.04
Provider you're deploying cluster on: AWS
Operating system you're deploying on: Amazon_Linux2
