### ISSUE TITLE
Error: The recommended value for "clusterDNS" in "KubeletConfiguration" is: [10.96.0.10]; the provided value is: [169.254.20.10]

### ISSUE THREAD

**Issue by shibumi** [kubermatic/kubeone#1296]
**What happened**:

`kubeone apply -m kubeone.yaml` fails on fresh flatcar VMs with the following error:
```
WARN[15:51:38 CET] Task failed, error was: + export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/sbin:/usr/local/bin:/opt/bin
+ PATH=/usr/bin:/bin:/usr/sbin:/sbin:/sbin:/usr/local/bin:/opt/bin
+ [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm init --config=./kubeone/cfg/master_0.yaml --ignore-preflight-errors=DirAvailable--var-lib-etcd,ImagePull
W0323 14:46:34.681414    1787 utils.go:69] The recommended value for "clusterDNS" in "KubeletConfiguration" is: [10.96.0.10]; the provided value is: [169.254.20.10]
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
: Process exited with status 1
```

I have no idea where this messages comes from. It's the exact same kubeone.yaml file like the one from a few months ago.

**What is the expected behavior**:

`kubeone apply -m kubeone.yaml` should bootstrap a new cluster successfully.

**How to reproduce the issue**:

try to bootstrap a new cluster with the following kubeone manifest to flatcar containers:
```
apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
name: ob-stage
versions:
  kubernetes: "1.20.0"
clusterNetwork:
  podSubnet: ""
  serviceSubnet: ""
  serviceDomainName: ""
  nodePortRange: ""
  cni:
    canal:
      mtu: 1450
cloudProvider:
  none: {}
features:
  podNodeSelector:
    enable: false
    config:
      configFilePath: ""
  podSecurityPolicy:
    enable: false
  podPresets:
    enable: false
  staticAuditLog:
    enable: false
    config:
      policyFilePath: ""
      logPath: "/var/log/kubernetes/audit.log"
      logMaxAge: 30
      logMaxBackup: 3
      logMaxSize: 100
  dynamicAuditLog:
    enable: false
  metricsServer:
    enable: true
  openidConnect:
    enable: false
    config:
      issuerUrl: ""
      clientId: "kubernetes"
      usernameClaim: "sub"
      usernamePrefix: "oidc:"
      groupsClaim: "groups"
      groupsPrefix: "oidc:"
      signingAlgs: "RS256"
      requiredClaim: ""
      caFile: ""
systemPackages:
  configureRepositories: true # it's true by default
addons:
  enable: false
  path: "./addons"
controlPlane:
  hosts:
  - publicAddress: '10.88.10.2'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
    taints:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
  - publicAddress: '10.88.10.3'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
    taints:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
  - publicAddress: '10.88.10.4'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
    taints:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
staticWorkers:
  hosts:
  - publicAddress: '10.88.10.11'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
  - publicAddress: '10.88.10.12'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
  - publicAddress: '10.88.10.13'
    sshUsername: core
    sshAgentSocket: 'env:SSH_AUTH_SOCK'
apiEndpoint:
  host: '10.88.10.10'
  port: 6443
machineController:
  deploy: false
```

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): v1.2.1 
Operating system:  Arch Linux
Provider you're deploying cluster on: Vsphere (static Workers only)
Operating system you're deploying on: flatcar linux VERSION=2765.2.1
