### ISSUE TITLE
Addons directory path is required even if using only embedded addons

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1496]
The users are still required to provide the addons directory path and have the directory created, even if using only addons embedded in the KubeOne binary.

For example, having a KubeOneCluster manifest such as this one will produce an error:

```yaml
apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
versions:
  kubernetes: 1.21.4
cloudProvider:
  aws: {}
addons:
  enable: true
  addons:
    - name: default-storage-class
```
