### ISSUE TITLE
Check whether required params for embedded addons are present

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubeone#1555]
**What happened**:

Here's a snippet from my KubeOneCluster manifest:
```
apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
addons:
    enable: true
    path: ./addons
    addons:
        - name: cluster-autoscaler
versions:
```

As you can see, I missed to configure the AUTOSCALER_VERSION param.

After applying this, I saw this funny issue:
```
  Warning  InspectFailed  3m53s (x558 over 124m)  kubelet            Failed to apply default image tag "k8s.gcr.io/autoscaling/cluster-autoscaler:${AUTOSCALER_VERSION}": couldn't parse image reference "k8s.gcr.io/autoscaling/cluster-autoscaler:${AUTOSCALER_VERSION}": invalid reference format
```

**What is the expected behavior**:

kubeone should probably fail before deploying addons, if required parameters are missing.

**How to reproduce the issue**:

See above - install e.g. the embedded cluster-autoscaler addon but don't specify any params.

**Anything else we need to know?**

Better examples wrt enabling the embedded addons would be nice.

**Information about the environment**:
KubeOne version (`kubeone version`): 1.3
