### ISSUE TITLE
Fix propagation of proxy settings from kubeone.yaml to apiserver env

### ISSUE THREAD

**Issue by michalvanco** [kubermatic/kubeone#1749]
**What happened**:
if you are having a definition of proxy and no_proxy settings in kubeone, these are propagated on first run to the apiserver manifest on control plane hosts.

Anyway if you update these proxy values, these are not refreshed after running `kubeone apply` or `kubeone apply --force-upgrade`. Only option to trigger that is to change for example the kubernetes version.

Example files:
```
# file: kubeone.yaml
apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
name: test
versions:
  kubernetes: '1.21.9'
proxy:
  http: 'http://xxx:8080'
  https: 'http://xxx:8080'
  noProxy: 'xxx,yyy,zzz'
```

```
# file: kube-apiserver.yaml
env:                                                                                                                                                                                                                                                                    
    - name: HTTP_PROXY                                                                                                                                                                                                                                                      
      value: http://xxx:8080                                                                                                                                                                                                                       
    - name: http_proxy                                                                                                                                                                                                                                                      
      value: http://xxx:8080                                                                                                                                                                                                                       
    - name: HTTPS_PROXY                                                                                                                                                                                                                                                     
      value: http://xxx:8080                                                                                                                                                                                                                       
    - name: https_proxy                                                                                                                                                                                                                                                     
      value: http://xxx:8080                                                                                                                                                                                                                       
    - name: NO_PROXY                                                                                                                                                                                                                                                        
      value: xxx,yyy,zzz                                                                                                                                                                  
    - name: no_proxy                                                                                                                                                                                                                                                        
      value: xxx,yyy,zzz
```

Login is happening here - https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/env.go#L27

There is also a related cause from k8s - https://github.com/kubernetes/kubernetes/commit/1eeb3f155fe76d8376dbcf7ee582bda1042e65f0

**What is the expected behavior**:
Proxy setting is updated at least when `--force-upgrade` is used.

**How to reproduce the issue**:
Follow the kubeone deployment with proxy settings, then add some new value and run kubeone apply (--force-upgrade) and check that values were not updated on control-plane.

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): 1.3.3
Operating system: CentOS
Provider you're deploying cluster on: bare-metal (static kubeone setup)
Operating system you're deploying on:
