### ISSUE TITLE
Test cluster provisioning - Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1768]
This Epic is a collector for issues related to testing cluster provisioning without OSM. Additional tickets with more details will be created for each supported provider.

Instructions for testing cluster provisioning:

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Follow instructions from the appropriate testing issue (e.g. create a Pod/LB Service/PV...)

If you're asked to run the conformance tests, use Sonobuoy in the certified conformance mode, such as (see https://github.com/cncf/k8s-conformance/blob/master/instructions.md for more details):

```
sonobuoy run --mode=certified-conformance
```

Note: the conformance tests should be run only on AWS.

If you're asked to enable the default-storage-class addon, you can do that by adding this to the KubeOneCluster manifest:

```yaml
addons:
  enable: true
  addons:
  - name: "default-storage-class"
```

If you're asked to enable OSM, you can do that by enabling the `operating-system-manager` addon:

```yaml
addons:
  enable: true
  addons:
  - name: "operating-system-manager"
```
