### ISSUE TITLE
Test cluster provisioning on Nutanix - Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1775]
For more details see instructions posted in #1768.

**Use the following manifest as a template:**

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: 1.21.8
cloudProvider:
  nutanix: {}
addons:
  enable: true
  addons:
  - name: "csi-nutanix"
  - name: "default-storage-class"
```

Operating Systems to be tested:

* [x] Ubuntu 20.04
* [x] CentOS 7

Supported Kubernetes versions (choose only one operating system -- for example, you can test 1.23.3 on all operating systems, and then test other versions only on Ubuntu):

* [x] 1.23.3
* [x] 1.22.6
* [x] 1.21.9
* [x] 1.20.15

Upgrades (you don't need to run conformance tests for upgrade tests, only verify that pods can be scheduled):

* [x] 1.22.6 -> 1.23.3
* [x] 1.21.9 -> 1.22.6
* [x] 1.20.15 -> 1.21.9

For each test, you should:

* Create a Nutanix PV and attach it to the pod
