### ISSUE TITLE
Test changing the maximum container log size and files -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1785]
Instructions:

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster
  * Make sure to add the following stanza to your KubeOneCluster manifest before applying the cluster for the first time (feel free to change values as appropriate):
    ```yaml
    …
    loggingConfig:
      containerLogMaxSize: “100Ki”
      containerLogMaxFiles: 3
    ```
  * Make sure to add the following stanza depending on container runtime that you’re testing.
  * For Docker:
    ```yaml
    …
    containerRuntime:
      docker: {}
    ```
  * For containerd:
    ```yaml
    …
    containerRuntime:
      containerd: {}
    ```
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Ensure that the container logs are rotated when size reaches provided value (e.g. 100Ki) and that the expected number of files is kept
  * For Docker clusters, logs are located in `/var/lib/docker/containers/<container id>/<container id>-json.log `
  * For containerd clusters, logs are located in `/var/log/containers/`

This test should be done for both Docker and containerd (as instructed above). Kubernetes version, operating system, and cloud provider don’t matter.

* [x] Docker
* [x] containerd
