### ISSUE TITLE
Test the unattended-upgrades addon on Ubuntu -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1787]
Instructions:

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster
* Enable `unattended-upgrades`, as follows **before** running `kubeone apply` for the first time:
  ```yaml
  …
  addons:
    enable: true
    addons:
    - name: unattended-upgrades
  ```
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Ensure the addon is deployed and running
* SSH into the node and make sure
   * `unattended-upgrades` package is installed; `dpkg -s unattended-upgrades`
   * Is enabled; `apt-config dump APT::Periodic::Unattended-Upgrade`
