### ISSUE TITLE
Test custom addons and overwriting embedded addons -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1791]
Instructions:

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster
  * Enable some embedded addon, e.g. the `cluster-autoscaler`, by adding the following stanza to your KubeOneCluster manifest before running `kubeone apply` for the first time:
    ```yaml
    …
    addons:
      enable: true
      addons:
      - name: cluster-autoscaler
    ```
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Ensure the addon is deployed
* Create an addons directory in the same directory as the KubeOneCluster manifest
* Edit the KubeOneCluster manifest to add the addons directory path
    ```yaml
    ...
    addons:
      enable: true
      path: "./adodns"
      addons:
      - name: cluster-autoscaler
    ```
* Take the addon manifests from the release archive or GitHub, and put it in the addons directory
  * Make sure to keep the directory structure. If you take `cluster-autoscaler`, you should have `./addons/cluster-autoscaler/cluster-autoscaler.yaml`
* Edit the addon manifest to add something (e.g. a label, annotation, something to the command, etc.)
* Run `kubeone apply`
* Ensure the addon is updated in the cluster
