### ISSUE TITLE
Test PodSecurityPolicy feature -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1792]
Instructions:

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster on AWS
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Edit the KubeOneCluster manifest to enable the PodSecurityPolicy feature:
    ```yaml
    ...
    features:
      podSecurityPolicy:
        enable: true
    ```
* Run `kubeone apply` to apply the required resources
* Run `kubeone apply --force-upgrade` to enable the PodSecurityPolicy feature
* Ensure the PSPs are working as expected
