### ISSUE TITLE
Test the ContainerdRegistry API -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1794]
API Reference: https://docs.kubermatic.com/kubeone/master/references/kubeone_cluster_v1beta2/#containerruntimecontainerd

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster
  * In additional to regular KubeOne config, make sure to have the following:
    ```yaml
    containerRuntime:
      containerd:
        registries:
          myunknown.tld:
            mirrors:
            - host1.tld
            - https://host2.tld
            tlsConfig:
              insecureSkipVerify: true
            auth:
              username: "user1"
              password: "insecure"
    ```
    all the above is describing imaginary registry, but it's OK to use exactly
    that info
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* SSH to the control-plane node machines and check of this info from the config
  is propagated to the containerd config `/etc/containerd/config.toml`.
* SSH to the worker node machines and check of this info from the config
  is propagated to the containerd config `/etc/containerd/config.toml`.

This test can be done on a single provider with a single Kubernetes version, but each operating system should be tested:

* [x] Ubuntu 20.04
* [x] CentOS 7
* [x] Flatcar
* [x] RHEL 8.5

It's recommended to run tests on AWS because AWS supports all 4 operating systems. You can use Kubernetes 1.22.3.
