### ISSUE TITLE
Test sourcing containerd auth config from the credentials file -- Test Release 1.4

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1795]
API Reference: https://docs.kubermatic.com/kubeone/master/references/kubeone_cluster_v1beta2/

* Download the latest KubeOne 1.4.0 release candidate
* Follow the [Create a Kubernetes cluster tutorial](https://docs.kubermatic.com/kubeone/master/tutorials/creating_clusters/) to create your cluster
  * Make sure to have the following in the [credentials file](https://docs.kubermatic.com/kubeone/master/guides/credentials/#credentials-file):
    ```yaml
    registriesAuth: |
      apiVersion: kubeone.k8c.io/v1beta2
      kind: ContainerRuntimeContainerd
      registries:
        registry-1.docker.io:
          auth:
            auth: "base64(<YOUR_USER>:<YOUR_PASSWORD>)"
    ```
  * Make sure to have containerd explicitly enabled in the KubeOne manifest
    ```yaml
    ...
    containerRuntime:
      containerd: {}
    ...
    ```
* Wait for machine-controller-managed nodes to join the cluster
* Ensure all pods are Running
* Create a private docker.io repository, push any image there and try to depoy
  it from this private repository

This test can be done on a single provider with a single Kubernetes version, but each operating system should be tested:

* [x] Ubuntu 20.04
* [x] CentOS 7
* [x] Flatcar
* [x] RHEL 8.5

It's recommended to run tests on AWS because AWS supports all 4 operating systems. You can use Kubernetes 1.23.3.

**Comment by dermorz** [comment]
I think `registriesAuth` as possible key should be documented explicitly in: https://docs.kubermatic.com/kubeone/master/guides/credentials/#credentials-file

**Comment by dermorz** [comment]
@xmudrii Sure, will do so. But before we have to find out what's wrong here.

This `credentials.yaml` gets parsed into a map mapping "auth" to an empty `v1beta2.ContainerdRegistry` struct.
```
registriesAuth: |
  apiVersion: kubeone.k8c.io/v1beta2
  kind: ContainerRuntimeContainerd
  registries:
    auth:
      docker.io:
        auth: "<redacted>"
```

This `credentials.yaml` doesn't get parsed at all: `Error: failed to initialize State: failed to build state: failed to load cluster: unable to load a given KubeOneCluster object: failed to apply dynamic defaults: failed to parse registriesAuth from credentials file: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field ContainerdRegistry.registries.auth of type v1beta2.ContainerdRegistryAuthConfig`
```
registriesAuth: |
  apiVersion: kubeone.k8c.io/v1beta2
  kind: ContainerRuntimeContainerd
  registries:
    docker.io:
      auth: "<redacted>"
```

**Comment by kron4eg** [comment]
@dermorz sorry, I've mistyped the structure for `registriesAuth`. The real structure is of course `map[ofstringsRegistrieNames]RegistrySettings`.

```yaml
registriesAuth: |
  apiVersion: kubeone.k8c.io/v1beta2
  kind: ContainerRuntimeContainerd
  registries:
    my-cool-registry.tld:
      auth:
        username: "stone"
        password: "bridge"
```

**Comment by kron4eg** [comment]
but I'll add strict unmarshal to avoid such problem

**Comment by dermorz** [comment]
Alright, I got really confused here. :)
```yaml
registriesAuth: |
  apiVersion: kubeone.k8c.io/v1beta2
  kind: ContainerRuntimeContainerd
  registries:
    docker.io:
      auth:
        auth: "<redacted>"
```
it is in my case.

I will add this to the docs in a separate PR. And probaby can close #1827.
