### ISSUE TITLE
AWS: pvc block in pending with k8s 1.23 and clould.external=false

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubeone#1814]
<!-- Please use this template if you're reporting a bug. Try to provide as much information as possible. 

If you're reporting a security issue, please check the guidelines for reporting security issues https://github.com/kubermatic/kubeone/blob/master/CONTRIBUTING.md#reporting-a-security-vulnerability

Thanks!
-->

**What happened**:
with k8s `1.23`  when  creating pvc pointing  storageClass with `provisioner: kubernetes.io/aws-ebs`, the pvc stay in pending 
with error `persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator`

**What is the expected behavior**:
pv should be created


**How to reproduce the issue**:
1. create a k8s `1.23.3` cluster on AWS with the following configuration 
  **kubeone.yaml:**
  ```yaml
  apiVersion: kubeone.k8c.io/v1beta2
  kind: KubeOneCluster
  versions:
    kubernetes: '1.23.3'
  cloudProvider:
    aws: {}
  addons:
    enable: true
    addons:
   - name: "default-storage-class"
  ```
2. ensure storage class exist 
  ```bash
  $ k get sc standard-v2 -o yaml          
                                                                                                                                                                                                                                                                                       
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"kubeone.io/addon":"default-storage-class","kubernetes.io/cluster-service":"true"},"name":"standard-v2"},"parameters":{"type":"gp2"},"provisioner":"kubernetes.io/aws-ebs","volumeBindingMode":"WaitForFirstConsumer"}
    storageclass.beta.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2022-02-07T09:17:27Z"
  labels:
    kubeone.io/addon: default-storage-class
    kubernetes.io/cluster-service: "true"
  name: standard-v2
  resourceVersion: "1054"
  uid: f9a76f60-9e79-46e6-854e-6373177a1935
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
  ```
3. create a sts
  ```yaml 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: nginx 
  serviceName: "nginx"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard-v2"
        resources:
          requests:
            storage: 1Gi
  ```

the sts stay in pending state
```bash
 k describe pvc
Name:          www-test-0
Namespace:     default
StorageClass:  standard-v2
Status:        Pending
Volume:
Labels:        app=nginx
Annotations:   volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: ip-172-31-155-79.eu-west-3.compute.internal
               volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       test-0
Events:
  Type    Reason                Age                From                         Message
  ----    ------                ----               ----                         -------
  Normal  WaitForFirstConsumer  19s                persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  ExternalProvisioning  13s (x3 over 19s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
```


**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): 
```json
{
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "1.4.0-rc.0",
    "gitCommit": "a42407f815ceb762457738b4041823fbb5e1f5a9",
    "gitTreeState": "",
    "buildDate": "2022-02-03T15:28:27Z",
    "goVersion": "go1.17.5",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "42",
    "gitVersion": "v1.42.4",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```
Operating system: MacOS
Provider you're deploying cluster on: AWS
Operating system you're deploying on: ubuntu
