### ISSUE TITLE
Azure: pvc AzureDisk block in pending with k8s 1.23 and clould.external=false

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubeone#1828]
<!-- Please use this template if you're reporting a bug. Try to provide as much information as possible. 

If you're reporting a security issue, please check the guidelines for reporting security issues https://github.com/kubermatic/kubeone/blob/master/CONTRIBUTING.md#reporting-a-security-vulnerability

Thanks!
-->

**What happened**:
with k8s `1.23`  when  creating pvc pointing  storageClass with `kubernetes.io/azure-disk`, the pvc stay in pending 
with error `waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator`

**What is the expected behavior**:
pv should be created


**How to reproduce the issue**:
1. create a k8s `1.23.3` cluster on Azure with the following configuration 
  **kubeone.yaml:**
  ```yaml
  apiVersion: kubeone.k8c.io/v1beta2
  kind: KubeOneCluster
  versions:
    kubernetes: '1.23.3'
  cloudProvider:
    azure: {}
    cloudConfig: |
    {
        "cloud": "AZUREPUBLICCLOUD",
        "tenantId": "<YOUR-TENANT-ID>",
        "subscriptionId": "<YOUR-SUBSCRIPTION-ID>",
        "aadClientId": "<YOUR-CLIENT-ID>",
        "aadClientSecret": "<YOUR-CLIENT-SECRET>",
        "resourceGroup": "<cluster-name>-rg",
        "location": "<YOUR-CLUSTER-REGION>",
        "vnetName": "<cluster-name>-vpc",
        "subnetName": "<cluster-name>-subnet",
        "routeTableName": "<cluster-name>-rt",
        "securityGroupName": "<cluster-name>-sg",
        "primaryAvailabilitySetName": "<cluster-name>-avset-workers",
        "useInstanceMetadata": true,
        "loadBalancerSku": ""
    }
  addons:
    enable: true
    addons:
    - name: "default-storage-class"
  ```
2. ensure storage class exist 
  ```bash
  $ k get sc standard -o yaml          
                                                                                                                                                                                                                                                                                       
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubeone.io/addon: default-storage-class
    kubernetes.io/cluster-service: "true"
  name: standard
parameters:
  kind: Managed
  storageaccounttype: Standard_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
  ```
3. create a sts
  ```yaml 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: nginx 
  serviceName: "nginx"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
  ```

the sts stay in pending state
```bash
$ k describe pvc www-test-0
Name:          www-test-0
Namespace:     default
StorageClass:  standard
Status:        Bound
Volume:        pvc-1858e0fd-ada1-43e7-87bb-3565eb06ae41
Labels:        app=nginx
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
               volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       test-0
Events:
  Type    Reason                 Age                    From                                                                    Message
  ----    ------                 ----                   ----                                                                    -------
  Normal  ExternalProvisioning   4m13s (x263 over 69m)  persistentvolume-controller waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator
```


**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): 
```json
{
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "1.4.0-rc.0",
    "gitCommit": "a42407f815ceb762457738b4041823fbb5e1f5a9",
    "gitTreeState": "",
    "buildDate": "2022-02-03T15:28:27Z",
    "goVersion": "go1.17.5",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "42",
    "gitVersion": "v1.42.4",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```
Operating system: MacOS
Provider you're deploying cluster on: Azure
Operating system you're deploying on: ubuntu
