### ISSUE TITLE
containerd-config is not being updated on flatcar control plane nodes

### ISSUE THREAD

**Issue by dermorz** [kubermatic/kubeone#1901]
**What happened**:
When changing the containerd config in the kubeone manifest the config is not being updated on flatcar control plane nodes.

**What is the expected behavior**:
The containerd config should be updated according to the changes in the manifest.

**How to reproduce the issue**:
1. Run kubeone with following manifest to install kubernetes on flatcar nodes:
```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: v1.23.3
cloudProvider:
  aws: {}
containerRuntime:
  containerd: {}
    registries:
      "*":
        mirrors:
          - https://docker-hub-proxy.gec.io
addons:
  enable: false
```
2. Change the manifest and run `kubeone apply --force-upgrade`:
```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: v1.23.3
cloudProvider:
  aws: {}
containerRuntime:
  containerd: {}
    registries:
      "docker.io":
        mirrors:
          - https://my.dockerhub.proxy
addons:
  enable: false
```
3. Check `/etc/containerd/config.toml` on the control plane nodes.

**Anything else we need to know?**
1. On initial install the containerd config is written correctly. This bug only affects updates.
2. This bug is flatcar specific, it works as expected on ubuntu control plane nodes.
3. The machine-controller is correctly updated. After forcing recreations of the worker nodes the new ones will have the correct containerd configs.

**Information about the environment**:
KubeOne version (`kubeone version`): v1.4.0
Operating system: Linux
Provider you're deploying cluster on: aws
Operating system you're deploying on: flatcar
