### ISSUE TITLE
Credentials for machine-controller are always created despite being disabled

### ISSUE THREAD

**Issue by dakraus** [kubermatic/kubeone#1902]
**What happened**:

I'm currently using KubeOne to deploy a cluster on vSphere but with pre-provisioned VMs only - meaning I have only static control plane / worker nodes defined in the KubeOne manifest and the deployment of the machine-controller is disabled. The external CCM / CSI driver for vSphere should still be used.

I tried to use the ability introduced in KubeOne 1.4 to specify different credentials for the CCM and machine-controller by setting only the variables `CCM_VSPHERE_SERVER`, `CCM_VSPHERE_USER` and `CCM_VSPHERE_PASSWORD` but `kubeone apply` failed with the following error message:
```
Error: failed to validate credentials: unable to validate credentials: key VSPHERE_SERVER is required but isn't present
failed to validate credentials: unable to validate credentials: key VSPHERE_SERVER is required but isn't present
make: *** [Makefile.kubeone:53: kubeone/apply] Error 255
```

Removing the `CCM_` prefix from these variables (or setting dummy values for the machine-controller specific variables) solves the problem and `kubeone apply` creates the cluster, but the secret for the machine-controller is still created:
```
k -n kube-system get secrets kubeone-machine-controller-credentials 
> NAME                                     TYPE     DATA   AGE
> kubeone-machine-controller-credentials   Opaque   3      20m
```

**What is the expected behavior**:

* The machine-controller specific credentials/variables should not be required if the machine-controller is disabled
* The secret for the machine-controller should not be created if the machine-controller is disabled

**How to reproduce the issue**:

credentials.yaml (`cloudConfig` and `csiConfig` omitted for brevity):
```yaml
CCM_VSPHERE_SERVER: "server"
CCM_VSPHERE_USER: "user"
CCM_VSPHERE_PASSWORD: "password"

cloudConfig: |
  ...
csiConfig: |
  ...
```

kubeone.yaml (full definition omitted for brevity):
```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

versions:
  kubernetes: 1.22.7
cloudProvider:
  external: true
  vsphere: {}
apiEndpoint:
  host: ...
  port: 6443
controlPlane:
  hosts: ...
staticWorkers:
  hosts: ...

machineController:
  deploy: false
```

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`):  v1.4.0
Operating system: Arch Linux
Provider you're deploying cluster on: vSphere
Operating system you're deploying on: Ubuntu 20.04.3
