### ISSUE TITLE
Upgrading cluster using Cilium from 1.23.5 to 1.23.6 causes pods to CrashLoopBackoff

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2021]
### What happened?

All pods restarted after upgrading Kubernetes from 1.23.5 to 1.23.6 are stuck in CrashLoopBackOff. Describing an affected pod shows:

```
  Warning  Unhealthy  3m29s (x9 over 4m)     kubelet            Readiness probe failed: Get "http://10.244.2.227:8085/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  3m26s (x4 over 3m58s)  kubelet            Readiness probe failed: Get "http://10.244.2.227:8085/healthz": dial tcp 10.244.2.227:8085: i/o timeout (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  3m26s (x4 over 3m56s)  kubelet            Liveness probe failed: Get "http://10.244.2.227:8085/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Expected behavior

* Pod networking is working after upgrading a cluster
* Pods restarted after upgrading the cluster are working as expected

### How to reproduce the issue?

* Create a Kubernetes cluster running 1.23.5 with Cilium as CNI (use the manifest provided below)
* Upgrade the cluster to 1.23.6
* Observe the pods getting stuck in CrashLoopBackoff

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "v1.4.2",
    "gitCommit": "e1ef6466e56fb543b011239faa42e32cd712101c",
    "gitTreeState": "",
    "buildDate": "2022-05-05T12:54:24+02:00",
    "goVersion": "go1.18.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "43",
    "gitVersion": "v1.43.2",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: 1.23.5
cloudProvider:
  aws: {}
clusterNetwork:
  cni:
    cilium:
      # enableHubble to deploy Hubble relay and UI
      enableHubble: true
      # kubeProxyReplacement defines weather cilium relies on underlying Kernel support to replace kube-proxy functionality by eBPF (strict),
      # or disables a subset of those features so cilium does not bail out if the kernel support is missing (disabled).
      kubeProxyReplacement: "disabled"
```

</details>

### What cloud provider are you running on?

AWS, but other providers are potentially affected as well.

### What operating system are you running in your cluster?

Ubuntu 20.04.

### Additional information

The issue can be mitigated by rolling out Cilium pods.

```
kubectl rollout restart daemonset -n kube-system cilium
```
