### ISSUE TITLE
Provisioning The Cluster k8s with kubeone

### ISSUE THREAD

**Issue by maticoul** [kubermatic/kubeone#2090]
### What happened?

after run kubeone apply -m kubeone.yaml and get this
Task failed, error was: + export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/sbin:/usr/local/bin:/opt/bin
+ PATH=/usr/bin:/bin:/usr/sbin:/sbin:/sbin:/usr/local/bin:/opt/bin
+ [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm init --config=./kubeone/cfg/master_0.yaml
W0602 20:40:18.191609    3010 utils.go:69] The recommended value for "clusterDNS" in "KubeletConfiguration" is: [10.96.0.10]; the provided value is: [169.254.20.10]
        [WARNING Hostname]: hostname "master01" could not be reached
        [WARNING Hostname]: hostname "master01": lookup master01 on 8.8.8.8:53: no such host
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
: Process exited with status 

### What KubeOne version are you using?

<details>

```console
$ kubeone version
# {
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "1.4.4",
    "gitCommit": "3d62a6ff07d0f3eacf9c9900acf8ccb71333466f",
    "gitTreeState": "",
    "buildDate": "2022-06-02T13:24:15Z",
    "goVersion": "go1.18.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "43",
    "gitVersion": "v1.43.3",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
# apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: k8scluster
versions:
  kubernetes: "1.23.0"
cloudProvider:
  none: {}
clusterNetwork:
  # the subnet used for pods  (default: 10.244.0.0/16)
  podSubnet: "192.168.0.0/16"
  cni:
    external: {}
addons:
  enable: true
  addons:
    - name: calico-vxlan
      params:
        MTU: "0" # auto-detect MTU
controlPlane:
  hosts:
    - privateAddress: '192.168.1.31'
      sshPrivateKeyFile: '/root/.ssh/id_rsa'
      sshUsername: flatcar
      hostname: master1
  #   taint: []
    - privateAddress: '192.168.1.32'
      sshPrivateKeyFile: '/root/.ssh/id_rsa'
      sshUsername: flatcar
      hostname: master2
- privateAddress: '192.168.1.33'
      sshPrivateKeyFile: '/root/.ssh/id_rsa'
      sshUsername: flatcar
      hostname: master3

# A list of static workers, not managed by MachineController.
# The list of nodes can be overwritten by providing Terraform output.
staticWorkers:
  hosts:
    - privateAddress: '192.168.1.34'
      sshPrivateKeyFile: '/root/.ssh/id_rsa'
      sshUsername: flatcar
      hostname: worker1
    - privateAddress: '192.168.1.35'
      sshPrivateKeyFile: '/root/.ssh/id_rsa'
      sshUsername: flatcar
      hostname: worker2
- privateAddress: '192.168.1.36'
      sshPrivateKeyFile: '/root/.ssh/id_rsa'
      sshUsername: flatcar
      hostname: worker3
apiEndpoint:
  host: '192.168.1.37'
  port: 6443
machineController:
  deploy: false
```

</details>

### What cloud provider are you running on?

on prim

### What operating system are you running in your cluster?

Flatcar Linux
