### ISSUE TITLE
[Azure external CCM] two controller compete for allocating node CIDR

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubeone#2104]
### What happened?

Used kubeone 1.4.4 with `external: true` with Azure cloud provider to enable external CCM. After the rollout, the nodes recycled and two of the worker nodes had weird networking issues.

In such scenarios - pods from nodes cannot reach the pods running on such conflicted nodes.

Upon digging through logs and events, we noticed that both nodes were allocated same CIDR block for pod ips.

@rastislavs helped zero in on the cause that kube-controller-manager and azure-cloud-controller-manager both were allocating CIDRs to nodes at the same time causing conflicting assignment.

He has fixed this in KKP in [this PR](https://github.com/kubermatic/kubermatic/pull/10098) but we need to fix this in kubeone as well.

### Expected behavior

Nodes should not get conflicting IP range for Azure external CSI

### How to reproduce the issue?

Issue does not always get reproduced since its a race condition between two controllers

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "1.4.3",
    "gitCommit": "717787f2287964e5793d80ec8ca2c2169936b0ac",
    "gitTreeState": "",
    "buildDate": "2022-05-11T14:18:03Z",
    "goVersion": "go1.18.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "43",
    "gitVersion": "v1.43.2",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: cldazkubermaticdev

versions:
  kubernetes: "1.22.8"

apiEndpoint:
  host: '10.xx.yy.zz'
containerRuntime:
  containerd: {}
cloudProvider:
  external: true
  azure: {}
clusterNetwork:
  nodePortRange: "30000-30199"
addons:
  enable: true
  path: "./addons" # always apply
  addons:
  - name: azure-sc
  - name: backup-restic
  - name: cluster-autoscaler
  - name: docker-pre-pull-daemonset
  - name: ntp-daemonset
  - name: k8s-event-logger
  - name: unattended-upgrades
    delete: true
```

</details>

### What cloud provider are you running on?

Azure

### What operating system are you running in your cluster?

Ubuntu 20.04
