### ISSUE TITLE
Test cluster provisioning on vSphere - Test Release KubeOne 1.5

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2245]
This is a ticket for tracking the progress of testing cluster provisioning on vSphere.

Follow instructions in #2232. vSphere **DOES NOT have** working automated E2E tests.

**Use the following manifest as a template:**

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: << VERSION >>
cloudProvider:
  vsphere: {}
  external: << true/false >>
  cloudConfig: |
    ...
  csiConfig: |
    ... # only if external
addons:
  enable: true
  addons:
  - name: "default-storage-class"
```

Operating Systems to be tested:

* [x] Ubuntu 20.04
* [x] CentOS 7
* [x] RHEL
* [x] Rocky Linux
* [x] Flatcar

Supported Kubernetes versions (choose only one operating system -- for example, you can test 1.24.3 on all operating systems, and then test other versions only on Ubuntu):

* [x] 1.24.3
* [x] 1.23.9
* [x] 1.22.12

OSM or legacy:

* [x] OSM
* [x] Legacy (machine-controller)

In-tree cloud provider or external:

* [x] In-tree cloud provider
* [x] External CCM

For each test, you should:

* Create a vSphere PV and attach it to the pod
