### ISSUE TITLE
Test cluster provisioning on VCD - Test Release KubeOne 1.5

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2246]
This is a ticket for tracking the progress of testing cluster provisioning on VMware Cloud Director (VCD).

Follow instructions in #2232. VCD **DOES NOT have** working automated E2E tests.

**Use the following manifest as a template:**

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: << VERSION >>
cloudProvider:
  vmwareCloudDirector: {}
```

Operating Systems to be tested:

* [x] Ubuntu 20.04

Supported Kubernetes versions (choose only one operating system -- for example, you can test 1.24.3 on all operating systems, and then test other versions only on Ubuntu):

* [x] 1.24.3
* [x] 1.23.9
* [x] 1.22.12

OSM or legacy:

* [x] OSM
* [x] Legacy (machine-controller)
