### ISSUE TITLE
Test cluster upgrading on Nutanix - Test Release KubeOne 1.5

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2254]
This is a ticket for tracking the progress of testing cluster upgrading on Nutanix.

Follow instructions in #2247. Nutanix **DOES NOT** have automated E2E tests.

**Use the following manifest as a template:**

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: << VERSION >>
cloudProvider:
  nutanix: {}
addons:
  enable: true
  addons:
  - name: "default-storage-class"
```

Operating Systems to be tested:

* [ ] Ubuntu 20.04
* [ ] CentOS 7

Upgrades (you don't need to run conformance tests for upgrade tests, only verify that pods can be scheduled):

* [ ] 1.23.9 -> 1.24.3
* [ ] 1.22.12 -> 1.23.9
