### ISSUE TITLE
Azure External CSI and kube-controller-manager volume-attachment conflict (race)

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubeone#2270]
### What happened?
With external CSI for Azure, sometimes, our volumes do not get bound with error "An operation with the given VolumeID xxx already exists"
Error message:
![Y0Szz6qtls](https://user-images.githubusercontent.com/1920926/183915299-a7d01663-67ad-4a8b-94f7-d26cc6537cce.png)

Upon closure look at logs, it appears that both, csi-azuredisk-controller and kube-controller-manager, try to attach volume and create conflict.
csi-azuredisk-controller logs:
![OVjP3YqWRv](https://user-images.githubusercontent.com/1920926/183915642-e998d973-28ed-4ef8-86c8-2a9e1a473516.png)

kube-controller-manager logs:
![HTaCesMCAO](https://user-images.githubusercontent.com/1920926/183915988-b941c3d8-0d59-4805-99c2-6201c18dccb8.png)

At this junction only solution that I am currently aware of is.. to delete the node where this conflict is happening.

### Expected behavior
Volume attachment should work without any issues

### How to reproduce the issue?
Unfortunately, there are not confirmed steps to reproduce the issue

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "1.4.4",
    "gitCommit": "3d62a6ff07d0f3eacf9c9900acf8ccb71333466f",
    "gitTreeState": "",
    "buildDate": "2022-06-02T13:24:15Z",
    "goVersion": "go1.18.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "43",
    "gitVersion": "v1.43.3",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: XXXXXX

versions:
  kubernetes: "1.22.9"
apiEndpoint:
  host: 'XXXX.xxx.xx.xx'
containerRuntime:
  containerd: {}
cloudProvider:
  external: true
  azure: {}
clusterNetwork:
  nodePortRange: "30000-30199"
addons:
  enable: true
  path: "./addons" # always apply
  addons:
  - name: azure-sc
  - name: backup-restic
  - name: cluster-autoscaler # Using default addon from kubeone now.
  - name: docker-pre-pull-daemonset
  - name: ntp-daemonset
  - name: k8s-event-logger
```

</details>

### What cloud provider are you running on?

Azure

### What operating system are you running in your cluster?

Ubuntu 20.04
