### ISSUE TITLE
coreDNS API: cleanup PDB if deployPodDisruptionBudget is disabled 

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubeone#2322]
If you have a cluster deployed with:
```
features:
  # Configure the CoreDNS deployment
  coreDNS:
    replicas: 3
    deployPodDisruptionBudget: true
```

and you disable `deployPodDisruptionBudget`, then you get no error.

The config is updated with `deployPodDisruptionBudget=false` but the `Poddisruptionbudgets` `coredns` is not deleted.

A cleanup should be done of the existing PDB when PDB is disabled for coreDNS
