### ISSUE TITLE
Deploy Operating System Profile with KubeOne

### ISSUE THREAD

**Issue by dcardellino** [kubermatic/kubeone#2341]
### Description of the feature you would like to add / User story

As a user of KubeOne I want to be able to deploy operating-system-profiles while I deploy my cluster, to use my custom profiles from the beginning.
Right now if you try to deploy OSP via KubeOne addon, you get templating errors like this:

```
WARN[09:54:50 CEST] Task failed, error was: runtime: executing addons manifest template "osp-ubuntu-custom.yaml"
template: addons-base:26:63: executing "addons-base" at <.Token>: can't evaluate field Token in type addons.templateData
WARN[09:55:00 CEST] Retrying task...
```

### Solution details

- operating-system-profile should be deployable via KubeOne Addon

**Comment by kron4eg** [comment]
@dcardellino what is .Token in your osp-ubuntu-custom.yaml?

**Comment by dcardellino** [comment]
@kron4eg I just duplicated the default osp-ubuntu, renamed it and made some small adjustments, but here you see:

```yaml
  bootstrapConfig:
    files:
      - path: /opt/bin/bootstrap
        permissions: 755
        content:
          inline:
            encoding: b64
            data: |
              #!/bin/bash
              set -xeuo pipefail
              export DEBIAN_FRONTEND=noninteractive
              apt update && apt install -y curl jq
              curl -s -k -v --header 'Authorization: Bearer {{ .Token }}'	{{ .ServerURL }}/api/v1/namespaces/cloud-init-settings/secrets/{{ .SecretName }} | jq '.data["cloud-config"]' -r| base64 -d > /etc/cloud/cloud.cfg.d/{{ .SecretName }}.cfg
              cloud-init clean
```
