### ISSUE TITLE
Add new node with controlplane

### ISSUE THREAD

**Issue by mxsavchenko** [kubermatic/kubeone#2373]
How to add new node with controlplane?
Cluster setup on bare metal.
I added a new node (`192.168.10.102`) to the section `controlPlane.hosts`:
```
controlPlane:
  hosts:
    - privateAddress: '192.168.10.101'
      sshUsername: root

    - publicAddress: '192.168.10.102'
      sshUsername: root
```
and run the command `kubeone -v apply` and i get an error:
```
DEBU[16:14:47 EEST] Hostname is detected: "node2.example.com"  node=192.168.10.102
INFO[16:14:47 EEST] Determine operating system...
DEBU[16:14:48 EEST] Operating system detected: "ubuntu"           node=192.168.10.102
INFO[16:14:48 EEST] Running host probes...
ERRO[16:14:50 EEST] ssh: popen
Process exited with status 1       node=192.168.10.102
WARN[16:14:53 EEST] Task failed, error was: runtime: running task on "192.168.10.102"
```
and so it goes in a circle.
The same node for staticWorkers was added without problems.

Versions:
Node OS - Ubuntu 20.04

```
kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "5",
    "gitVersion": "1.5.0-rc.0",
    "gitCommit": "16c6bdfd0d219cd1ff0b4beeb9fcdf89d815d84c",
    "gitTreeState": "",
    "buildDate": "2022-08-25T13:18:09Z",
    "goVersion": "go1.19",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "54",
    "gitVersion": "v1.54.0",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

My kubeone config:
```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: test-cluster

versions:
  kubernetes: "1.23.9"

cloudProvider:
  none: {}

controlPlane:
  hosts:
    - privateAddress: '192.168.10.101'
      sshUsername: root

    - privateAddress: '192.168.10.102'
      sshUsername: root

staticWorkers:
  hosts:
    - privateAddress: '192.168.10.101'
      sshUsername: root

    - privateAddress: '192.168.10.102'
      sshUsername: root

apiEndpoint:
  host: ''
  port: 6443
  alternativeNames: []

machineController:
  deploy: false

operatingSystemManager:
  deploy: false

loggingConfig:
  containerLogMaxSize: "100Mi"
  containerLogMaxFiles: 5
```
