### ISSUE TITLE
Improve config for unattended-upgrades addon

### ISSUE THREAD

**Issue by sphr2k** [kubermatic/kubeone#2408]
### Description of the feature you would like to add / User story

As a user I would like to be able to configure the configuration flags for _kured_ without having to replace the embedded addon with a custom one.

### Solution details

Implement kured flags as addon parameters

**Comment by kron4eg** [comment]
We dropped support for out own kubed addon in favor of upstream helm chart (with helm of `helmReleases`).

You can have it with something like
```yaml
helmReleases:
  - chart: kured
    repoURL: https://kubereboot.github.io/charts
    namespace: kube-system
    version: 5.4.2
```

and customize any aspect listed in the chart (https://github.com/kubereboot/charts/blob/main/charts/kured/templates/daemonset.yaml#L66)
