### ISSUE TITLE
Kubeone fails to run "ssh: installing kubeadm"

### ISSUE THREAD

**Issue by lukas-at-harren** [kubermatic/kubeone#2574]
### What happened?

During a vanilla installation this happened.

```
[...snip...]
+ curl -fsSL https://download.docker.com/linux/ubuntu/gpg
curl: (22) The requested URL returned error: 403
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
```

It seems the download from https://download.docker.com/linux/ubuntu/gpg can return a 403 forbidden response.
I don't know the reason behind this, it is certainly a public API.

Maybe you can reduce the reliance on unreliable 3rd parties?

What is weird, I configured the server to run with `containerd` so why does Docker still play a role?

See my `kubeone.yml` manifest.

### Expected behavior

Kubeone installs just fine.

### How to reproduce the issue?

Use the `kubeone.yml` from above and install a new cluster according to the Kubeone example.

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "5",
    "gitVersion": "1.5.4",
    "gitCommit": "d814bd9007381d0eb06fefb4f7345a128b8f8666",
    "gitTreeState": "",
    "buildDate": "2022-12-12T09:37:23Z",
    "goVersion": "go1.19.4",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "54",
    "gitVersion": "v1.54.2",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.24.9'
clusterNetwork:
  cni:
    canal:
      # Note: Hetzner specific is 1400 (1450 bytes - 50 VXLAN bytes)
      mtu: 1400
cloudProvider:
  hetzner: {}
  external: true
containerRuntime:
  containerd: {}
```

</details>

### What cloud provider are you running on?

Hetzner

### What operating system are you running in your cluster?

ubuntu-20.04
