### ISSUE TITLE
Disallow using same machines for both control plane and static workers

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2632]
### Description of the feature you would like to add / User story

KubeOne considers the following config as "valid":

```yaml
...
controlPlane:
  hosts:
    - publicAddress: '192.168.1.2'
      privateAddress: '192.168.1.2'

staticWorkers:
  hosts:
    - publicAddress: '192.168.1.2'
      privateAddress: '192.168.1.2'
```

Such a config cannot produce a working cluster, as you can't reuse the same machine for both a control plane and a static worker. Instead, you can untaint the control plane node and schedule all the workload there.

### Solution details

- KubeOne validation should reject such a config
