### ISSUE TITLE
KubeOne fails to download the GPG key from `packages.cloud.google.com`

### ISSUE THREAD

**Issue by dcardellino** [kubermatic/kubeone#2705]
### What happened?

Upgrading Kubernetes from Version 1.25.6 to 1.26.1 fails with the following error:

```
WARN[12:39:14 CET] Task failed, error was: runtime: running task on "116.203.139.92"
ssh: upgrading kubeadm and CNI plugins
ssh: exec
ssh: popen
Process exited with status 2
set -xeuo pipefail
...
...
...
W: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://apt.kubernetes.io/dists/kubernetes-xenial/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
+ sudo DEBIAN_FRONTEND=noninteractive apt-get install --option Dpkg::Options::=--force-confold -y --no-install-recommends apt-transport-https ca-certificates curl gnupg lsb-release rsync
+ curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg
+ sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
curl: (22) The requested URL returned error: 500
gpg: no valid OpenPGP data found.
```

Running the command `curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg` is the one which is causes the actual error.

### Expected behavior

KubeOne can upgrade Kubernetes.

### How to reproduce the issue?

See in What happened?

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "6",
    "gitVersion": "1.6.0",
    "gitCommit": "8b0973ca77856dca920798bbd5ff6b5c0f3f4856",
    "gitTreeState": "",
    "buildDate": "2023-02-23T19:25:26Z",
    "goVersion": "go1.19.6",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "56",
    "gitVersion": "v1.56.0",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: v1.26.1
cloudProvider:
  hetzner: {}
  external: true
containerRuntime:
  containerd: {}
clusterNetwork:
  kubeProxy:
    ipvs: {}
features:
  coreDNS:
    replicas: 3
  staticAuditLog:
    enable: true
    config:
      policyFilePath: "audit-policy.yaml"
      logPath: "/var/log/kubernetes/audit/audit.log"
      logMaxAge: 30
      logMaxBackup: 3
      logMaxSize: 100
addons:
  enable: true
  path: "./addons"
```

</details>

### What cloud provider are you running on?

Hetzner
### What operating system are you running in your cluster?

Ubuntu 22.04
