### ISSUE TITLE
Update Hetzner CSI Driver to >v2.1.1 

### ISSUE THREAD

**Issue by 7oku** [kubermatic/kubeone#2721]
### What happened?

We updated to kubeone 1.6. After the update new nodes are unable to mount Hetzner block storage volumes (we are using them with rook-ceph). Reason is a bug in Hetzner CSI v2.1.0 mentioned in https://github.com/hetznercloud/csi-driver/issues/278. The issue was fixed in v2.1.1 (current is v2.2.0). 

We manually had to update the hcloud-csi DaemonSet to v2.1.1. After removing any related VolumeAttachment, the new csi driver was able to mount the block storage volume.

### Expected behavior

Nodes should be able to mount Hetzner volumes

### How to reproduce the issue?

Create a block storage volume at Hetzner with kubeone 1.5, update to kubeone 1.6, and rotate the workers. Workers will not be able to mount the block storages.

### What KubeOne version are you using?

kubeone v1.6

### Provide your KubeOneCluster manifest here (if applicable)

```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.24.10'
cloudProvider:
  hetzner: {}
  external: true
clusterNetwork:
  kubeProxy:
    skipInstallation: true
  cni:
    cilium:
      enableHubble: true
      kubeProxyReplacement: strict
addons:
  enable: true
  addons:
  - name: default-storage-class
```

### What cloud provider are you running on?

Hetzner

### What operating system are you running in your cluster?

Ubuntu 20.04

### Additional information

The issue is already fixed upstream, so quick resolution would be to just bump Hetzner CSI driver to >v2.1.1
