### ISSUE TITLE
Possibility to deactivate vSphere CSI

### ISSUE THREAD

**Issue by steled** [kubermatic/kubeone#2750]
### Description of the feature you would like to add / User story

As a KubeOne user
I would like to have the ability to deactivate the vSphere CSI
in order to be able to deploy a cluster without vSphere CSI

### Solution details

- disable vSphere CSI
- deploy cluster without putting a `csiConfig` to the `KubeOneCluster` configuration

### Use cases

I want to use the vSphere provider but without the vSphere CSI because I want to use Ceph as a storage backend.
The problem is if I only put the following lines of code into the `KubeOneCluster` config is that the pods of the `vsphere-csi-controller` deployment run into a `CrashLoopBackOff`.

```yaml
cloudProvider:
  vsphere: {}
  external: true
  csiConfig: |
    [VirtualCenter "<VCENTER>"]
cloudConfig: |
<omitted for brevity>
```

### Additional information

You can also check https://github.com/kubermatic/kubeone/issues/2737 for some background information.
