### ISSUE TITLE
helmReleases not workin correctly

### ISSUE THREAD

**Issue by steled** [kubermatic/kubeone#2800]
### Expected behavior

The Helm chart of F5 BIG IP controller is installed.

### How to reproduce the issue?

Add the following `helmReleases` lines to the `kubeone.yaml` file and run `kubeone apply`:

```yaml
helmReleases:
  - releaseName: f5-bigip-ctlr
    chart: f5-bigip-ctlr
    repoURL: https://f5networks.github.io/charts/stable
    namespace: kube-system
    version: 0.0.25
    values:
      - valuesFile: ./helm/f5/controller-values.yaml
```

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "6",
    "gitVersion": "1.6.2",
    "gitCommit": "184adc3b7d0c1e2e7630ded518cbfdfab7300755",
    "gitTreeState": "",
    "buildDate": "2023-04-14T11:20:23Z",
    "goVersion": "go1.19.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "56",
    "gitVersion": "v1.56.2",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: "1.26.4"
cloudProvider:
  vsphere: {}
  external: true
  cloudConfig: |
    [Global]
    secret-name = "vsphere-ccm-credentials"
    secret-namespace = "kube-system"
    port = "443"
    insecure-flag = "1"

    [VirtualCenter "<VCENTER-FQDN>"]

    [Workspace]
    server = "<VCENTER-FQDN>"
    datacenter = "<DATACECNTER>"
    default-datastore="<DATASTORE>"
    resourcepool-path="Others"
    folder = "/Customers/TEST/TEST Kubermatic"

    [Disk]
    scsicontrollertype = pvscsi

    [Network]
    public-network = "dPG_0705_Kubernetes-root"
  csiConfig: |
    [Global]
    # Unique identifier; name of the cluster
    cluster-id = "management-cluster"
    # TODO: CHANGE ME
    user = "<SERVICEACCOUNT>"
    # TODO: CHANGE ME
    password = "<PASSWORD>"
    port = "443"
    insecure-flag = "true"

    [VirtualCenter "<VCENTER-FQDN>"]
    # List of comma separated datacenters where node VMs are present
    datacenters = "<DATACENTER>"

containerRuntime:
  containerd: {}

clusterNetwork:
  cni:
    cilium:
      kubeProxyReplacement: disabled
      enableHubble: true

addons:
  enable: true
  path: "./addons"
  addons:
    - name: default-storage-class
    - name: cluster-autoscaler
    - name: custom-operating-system-profiles
      disableTemplating: true

helmReleases:
  - releaseName: f5-bigip-ctlr
    chart: f5-bigip-ctlr
    repoURL: https://f5networks.github.io/charts/stable
    namespace: kube-system
    version: 0.0.25
    values:
      - valuesFile: ./helm/f5/controller-values.yaml
  - releaseName: f5-ipam-controller
    chart: f5-ipam-controller
    repoURL: https://f5networks.github.io/f5-ipam-controller/helm-charts/stable
    namespace: kube-system
    version: 0.0.4
    values:
      - valuesFile: ./helm/f5/ipam-values.yaml
```

</details>

### What cloud provider are you running on?

VMware vSphere

### What operating system are you running in your cluster?

Ubuntu 22.04

### Additional information

When I run `kubeone apply` without `helmReleases` I see no CRDs with `kubectl get crd | grep f5`
After I add the `helmReleases` part back and run `kubeone apply` again I see the following:

```shell
$ kubectl get crd | grep f5
externaldnses.cis.f5.com                                2023-06-12T16:25:14Z
ingresslinks.cis.f5.com                                 2023-06-12T16:25:14Z
policies.cis.f5.com                                     2023-06-12T16:25:14Z
tlsprofiles.cis.f5.com                                  2023-06-12T16:25:14Z
transportservers.cis.f5.com                             2023-06-12T16:25:14Z
virtualservers.cis.f5.com                               2023-06-12T16:25:14Z
```

And I get the following error from `kubeone`:

```shell
DEBU[18:25:03 CEST] getting history for release f5-bigip-ctlr
INFO[18:25:03 CEST] Deploying helm chart f5-bigip-ctlr as release f5-bigip-ctlr
DEBU[18:25:04 CEST] creating 6 resource(s)
DEBU[18:25:04 CEST] Clearing discovery cache
DEBU[18:25:04 CEST] beginning wait for 6 resources with timeout of 1m0s
WARN[18:25:06 CEST] Task failed, error was: runtime: installing helm release "f5-bigip-ctlr" from chart "f5-bigip-ctlr"
rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "virtualservers.cis.f5.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "f5-bigip-ctlr"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
WARN[18:25:16 CEST] Retrying task...
```

If I check `$ kubectl get crd virtualservers.cis.f5.com -oyaml | grep anno` I see nothing.
But at least for the labels I can see something from `Helm`:

```shell
$ k get crd virtualservers.cis.f5.com -oyaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2023-06-12T16:25:14Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: f5-bigip-ctlr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: f5-bigip-ctlr
  name: virtualservers.cis.f5.com
  resourceVersion: "5400"
  uid: bedc465e-d37b-44c2-9707-acd5e8e14dcc
```
