### ISSUE TITLE
.cloudProvider.disableBundledCSIDrivers mandatoriness in docs/kubeone

### ISSUE THREAD

**Issue by 7oku** [kubermatic/kubeone#2914]
### What happened?

It may sound a bit pedantic, but we cannot wrap our head around correctly setting the API field `.cloudProvider.disableBundledCSIDrivers`, when upgrading clusters from kubeone versions prior 1.7.0. 

A first upgrade on a cluster having that CSI drivers installed already succeeded without error. Expected, since there is no explicit hint in the upgrade notes to give special attention to this setting. However, according the docs this is (the one and only) mandatory field (required: true at https://docs.kubermatic.com/kubeone/v1.7/references/kubeone-cluster-v1beta2/). 

Is this a bug in docs and the option is not really required or does kubeone just not complain about this mandatory field when it isn't being set? If latter, what is the default value (true or false)? 

### Expected behavior

Either 
- correct docs to have `.cloudProvider.disableBundledCSIDrivers` be optional, but with an expected default value (for me that would be `false` to follow behavior pre v1.7.0) 
or
- have kubeone fail with error, if the value is not present in kubeone.yml

### How to reproduce the issue?

Run kubeone >=v1.7.0 without setting `.cloudProvider.disableBundledCSIDrivers` in kubeone.yml

### What KubeOne version are you using?

<details>

```bash
./kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "7",
    "gitVersion": "1.7.0",
    "gitCommit": "1195366fd0cf11f314d194a3b29b6a782afde9a8",
    "gitTreeState": "",
    "buildDate": "2023-09-08T14:02:33Z",
    "goVersion": "go1.20.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "57",
    "gitVersion": "v1.57.3",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.26.8'
cloudProvider:
  hetzner: {}
  external: true
clusterNetwork:
  kubeProxy:
    skipInstallation: true
  cni:
    cilium:
      enableHubble: true
      kubeProxyReplacement: strict
addons:
  enable: true
  addons:
  - name: default-storage-class
```

</details>

Hetzner

### What operating system are you running in your cluster?

Ubuntu 20.04
