### ISSUE TITLE
Upgrade from 1.26.x to 1.27.x fails due to presence of deprecated kubelet flag (--container-runtime=remote)

### ISSUE THREAD

**Issue by teksuo** [kubermatic/kubeone#2924]
### What happened?

Upgrading a MachineDeployment from 1.26.6 to 1.27.6 (also tried with 1.27.3) fails because of kubelet flag "--container-runtime" is still present.

### Expected behavior

The upgrade should work without manual intervention.

### How to reproduce the issue?

- I upgraded the control plane without a problem with my pipeline using `kubeone apply -y -v -d -m $ENV_DIR/kubeone.yaml -t $ENV_DIR/tf-output.json --upgrade-machine-deployments`. 
- Then I changed the kubelet version of one of the MachineDeployments in order to start the rolling update of the Machines (don't know if I can actually do this automatically somehow...).
- The new created VMs are restarted over and over after some timeout unles the `--container-runtime` flag is deleted manually from `/etc/systemd/system/kubelet.service`.

### What KubeOne version are you using?

1.7.0

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "7",
    "gitVersion": "1.7.0",
    "gitCommit": "1195366fd0cf11f314d194a3b29b6a782afde9a8",
    "gitTreeState": "",
    "buildDate": "2023-09-08T14:02:33Z",
    "goVersion": "go1.20.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "57",
    "gitVersion": "v1.57.3",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
# nonk8s
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.27.6'
cloudProvider:
  hetzner: {}
  external: true
addons:
  enable: true
  path: ../../config/extra/addons
  addons:
    - name: cluster-autoscaler
    - name: unattended-upgrades
```

</details>

### What cloud provider are you running on?

Hetzner Cloud

### What operating system are you running in your cluster?

Ubuntu 22.04
