### ISSUE TITLE
Cilium CNI `hubble-relay` deployment problems

### ISSUE THREAD

**Issue by mhkarimi1383** [kubermatic/kubeone#2970]
### What happened?

Deployed KubeOne cluster using Cilium CNI with Hubble enabled

And it's getting

```
MountVolume.SetUp failed for volume "tls" : secret "hubble-relay-client-certs" not found
```

I think there is a problem with `hubble-relay` deployment manifest template

The only thing that I found related to this problem was https://github.com/cilium/cilium/issues/13537

### Expected behavior

Having `hubble-relay` available 

### How to reproduce the issue?

Deploy a Cluster with configuration below (Tested in `bare-metal` environment)

```yaml
clusterNetwork:
  cni:
    cilium:
      enableHubble: true
      kubeProxyReplacement: strict
  kubeProxy:
    skipInstallation: true
```

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "7",
    "gitVersion": "v1.7.0",
    "gitCommit": "1195366fd0cf11f314d194a3b29b6a782afde9a8",
    "gitTreeState": "",
    "buildDate": "2023-10-04T14:55:11+00:00",
    "goVersion": "go1.21.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "57",
    "gitVersion": "v1.57.3",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: karimi-hub

cloudProvider:
  none: {}

versions:
  kubernetes: v1.27.6

containerRuntime:
  containerd: {}

clusterNetwork:
  cni:
    cilium:
      enableHubble: true
      kubeProxyReplacement: strict
  kubeProxy:
    skipInstallation: true
machineController:
  deploy: false

operatingSystemManager:
  deploy: false


controlPlane:
  hosts:
    - privateAddress: '1.1.1.1'
      publicAddress: '1.1.1.1'
      sshUsername: root
      sshPrivateKeyFile: '/path/to/my/private-key'
      taints:
        - key: "node-role.kubernetes.io/control-plane"
          effect: "NoSchedule"

staticWorkers:
  hosts:
    - privateAddress: '1.1.1.2'
      publicAddress: '1.1.1.2'
      sshUsername: root
      sshPrivateKeyFile: '/path/to/my/private-key'

apiEndpoint:
  host: "1.1.1.1"
  port: 6443
```

</details>

### What cloud provider are you running on?

Other (Bare Metal)

### What operating system are you running in your cluster?

Debian 12 (Bookworm)
