### ISSUE TITLE
kubeone 1.7 upgrade - Azure - ClusterRoleBinding csi-azuredisk-node-secret-binding migration failure

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubeone#2971]
### What happened?
On Azure, when we upgraded kubeone 1.6 to 1.7.1, we saw that addons installation failed due to change of Role name in immutable `ClusterRoleBinding` named `csi-azuredisk-node-secret-binding`

This role name was changed in this PR #2831 where in the diff you can see that there was a warning to not change this name,

This causes kubeone installation to get stuck in a loop in trying to install the default addons. Mitigation was to delete the CRB manually and then kubeone created new one and proceeded forward.

### Expected behavior
Kubeone installation should take care of migraton of this CRB intrinsically.

### How to reproduce the issue?
1. Install kubeone 1.6 on Azure with k8s version 1.25+ and use External CSI
2. Upgrade kubeone via kubeone apply with newer version of kueone 1.7.1

### What KubeOne version are you using?
kubeone 1.7.1

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "7",
    "gitVersion": "1.7.1",
    "gitCommit": "8b010b26a2e2337ccbc49dddf08a83976bee98d8",
    "gitTreeState": "",
    "buildDate": "2023-11-10T11:22:01Z",
    "goVersion": "go1.21.3",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "57",
    "gitVersion": "v1.57.3",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: kubeoneClust1

versions:
  kubernetes: "1.27.8"

containerRuntime:
  containerd:
    registries:
      docker.io:
        mirrors:
        - https://mirror1.com
      gcr.io:
        mirrors:
        - https://mirror1.com
      quay.io:
        mirrors:
        - https://mirror1.com
      registry.k8s.io:
        mirrors:
        - https://mirror1.com
      mcr.microsoft.com:
        mirrors:
        - https://mirror1.com
cloudProvider:
  external: true
  azure: {}
clusterNetwork:
  nodePortRange: "30000-30199"
  cni:
    cilium:
      kubeProxyReplacement: "strict"
      enableHubble: true
  kubeProxy:
    skipInstallation: true
systemPackages:
  configureRepositories: false

addons:
  enable: true
  path: "./addons" # always apply
  addons:
  - name: azure-sc
  - name: backup-restic
  - name: cluster-autoscaler
    params:
      CLUSTER_AUTOSCALER_SKIP_LOCAL_STORAGE: "false"
      CLUSTER_AUTOSCALER_SCALE_DOWN_UTIL_THRESHOLD: "0.6"
  - name: ntp-daemonset
  - name: k8s-event-logger
  - name: unattended-upgrades
    delete: true
  - name: operating-system-profiles
    disableTemplating: true

```

</details>

### What cloud provider are you running on?
Azure

### What operating system are you running in your cluster?
Ubuntu 22.04
