### ISSUE TITLE
helmReleases put objects to default namespace

### ISSUE THREAD

**Issue by artoff** [kubermatic/kubeone#2973]
### What happened?

Helm charts often contain explicit namespace definition in templates.

The good example is ArgoCD server [deployment template](https://github.com/argoproj/argo-helm/blob/argo-cd-5.51.6/charts/argo-cd/templates/argocd-server/deployment.yaml#L3).
Here we can see the following line in metadata section:
```yaml
namespace: {{ .Release.Namespace | quote }}
```

Rendered template then looks like
```yaml
# helm repo add argo https://argoproj.github.io/argo-helm && helm repo update
helm template argocd argo/argo-cd --version=5.51.6 -n argocd | grep argo-cd\/templates\/argocd-server\/deployment.yaml -A 15

# Source: argo-cd/templates/argocd-server/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: "argocd"
  labels:
    helm.sh/chart: argo-cd-5.51.6
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.9.3"
spec:
  replicas: 1
```

This is not the case for some other Helm charts.
Hedlamp [deployment template](https://github.com/headlamp-k8s/headlamp/blob/v0.17.1/charts/headlamp/templates/deployment.yaml#L3) do not state namespace explicitly.

Rendered template then looks like
```yaml
# helm repo add headlamp https://headlamp-k8s.github.io/headlamp/ && helm repo update
helm template headlamp headlamp/headlamp --version=0.17.1 -n headlamp | grep headlamp\/templates\/deployment.yaml -A 12

# Source: headlamp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  labels:
    helm.sh/chart: headlamp-0.17.1
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: headlamp
    app.kubernetes.io/version: "0.21.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
```

It is possible to install both kinds of Helm charts by Helm commandline tool without issues.

```bash
helm upgrade argocd argo/argo-cd --version=5.51.6 -n argocd --install --create-namespace
```
```bash
helm upgrade headlamp headlamp/headlamp --version=0.17.1 -n headlamp --install --create-namespace
```

Putting the following snippet into helmReleases section in kubeone manifest results in objects deployed in default namespace.
```yaml
  - releaseName: headlamp
    chart: headlamp
    repoURL: https://headlamp-k8s.github.io/headlamp/
    namespace: headlamp
    version: 0.17.1
```

This happens to a fresh new cluster. The first and subsequent `kubeone apply` gives the same results.

### Expected behavior

helmReleases behavior in the same way as in Helm commandline tool.

### How to reproduce the issue?

Put the snippet into helmReleases section in kubeone manifest and run `kubeone apply`. 

```yaml
  - releaseName: headlamp
    chart: headlamp
    repoURL: https://headlamp-k8s.github.io/headlamp/
    namespace: headlamp
    version: 0.17.1
```

### What KubeOne version are you using?

```json
{
  "kubeone": {
    "major": "1",
    "minor": "7",
    "gitVersion": "1.7.1",
    "gitCommit": "8b010b26a2e2337ccbc49dddf08a83976bee98d8",
    "gitTreeState": "",
    "buildDate": "2023-11-10T11:22:01Z",
    "goVersion": "go1.21.3",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "57",
    "gitVersion": "v1.57.3",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

### Provide your KubeOneCluster manifest here (if applicable)

Kubernetes version could be relevant

```yaml
versions:
  kubernetes: 1.27.5
```

### What cloud provider are you running on?

baremetal

### What operating system are you running in your cluster?

Ubuntu 22.04

### Additional information

It looks like Helm commandline tool is doing something which is [missing from the kubeone currently](https://github.com/kubermatic/kubeone/issues/2800#issuecomment-1621617786).
