### ISSUE TITLE
KubeOne does not detect containerd version on Flatcar Linux

### ISSUE THREAD

**Issue by spimmer** [kubermatic/kubeone#3049]
### What happened?

When trying to provision a KubeOne cluster on Flatcar nodes, KubeOne fails to detect containerd version and cancels installation.

### Expected behavior

KubeOne succeeds to detect containerd version and continues installation.

### How to reproduce the issue?

- provision a node with flatcar
- try to run `kubeone apply`against that node

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "7",
    "gitVersion": "1.7.2",
    "gitCommit": "00fd09d91da76e307f016afb3b4f42ad6281eb2c",
    "gitTreeState": "",
    "buildDate": "2024-01-05T15:30:12Z",
    "goVersion": "go1.21.3",
    "compiler": "gc",
    "platform": "darwin/arm64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "57",
    "gitVersion": "v1.57.4",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
}
```

</details>

Confirmed same behavior with KubeOne v1.7.0

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: flatcar
versions:
  kubernetes: '1.27.11'
cloudProvider:
  none: {}
controlPlane:
  hosts:
    - hostname: flatcar
      publicAddress: '10.10.10.10'
      privateAddress: '10.10.10.10'
      sshUsername: core
      sshPrivateKeyFile: 'flatcar'
      taints: []
clusterNetwork:
  cni:
    cilium:
      kubeProxyReplacement: strict
  kubeProxy:
    skipInstallation: true
apiEndpoint:
  host: '10.10.10.10'
  port: 6443
  alternativeNames:
    - flatcar

machineController:
  deploy: false

operatingSystemManager:
  deploy: false
```

</details>

### What cloud provider are you running on?

VMware vSphere (without Terraform or any integration)

### What operating system are you running in your cluster?

Flatcar Linux

### Additional information

Output of `kubectl apply`:
```
$ ./kubeone apply --manifest ./kubeone.yaml -y -vvv                                                                                                                                                     130 ↵
INFO[14:16:23 CET] Determine hostname...
DEBU[14:16:24 CET] Hostname is already set to "flatcar"  node=10.10.10.10
INFO[14:16:24 CET] Determine operating system...
DEBU[14:16:24 CET] Operating system detected: "flatcar"          node=10.10.10.10
INFO[14:16:24 CET] Running host probes...
ERRO[14:16:24 CET] containerd version was: "": Invalid Semantic Version  node=10.10.10.10
WARN[14:16:24 CET] Task failed, error was: runtime: running task on "10.10.10.10"
containerd version was: "": Invalid Semantic Version
^C
```
Flatcar OS information:
```
core@flatcar~ $ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3815.2.0
VERSION_ID=3815.2.0
BUILD_ID=2024-02-12-2039
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3815.2.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3815.2.0:*:*:*:*:*:*:*"
```

Flatcar butane config:
```yaml
variant: flatcar
version: 1.0.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - <ssh public keys>
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: |-
          flatcar
```
