### ISSUE TITLE
kubeone fails when nodes have hostname in all caps

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubeone#3071]
### What happened?

When creating a cluster it fails with the following error message:

```sh
INFO[16:03:22 CET] Applying addon nodelocaldns...               
WARN[16:03:24 CET] Task failed, error was: kubernetes: updating NUC-1 Node
nodes "NUC-1" not found 
WARN[16:03:34 CET] Retrying task...                             
WARN[16:03:34 CET] Task failed, error was: kubernetes: updating NUC-1 Node
nodes "NUC-1" not found 
```

When running `kubectl get nodes` we can see that the nodes are named "nuc-1" and "nuc-2, so all lowercase, not uppercase like in the log output above.

Indeed after resetting the cluster and changing all hostnames to lowercase on the nodes, the next kubeone run finishes successfully.

### Expected behavior

Cluster to be provisioned successfully.

### How to reproduce the issue?

1. Create some VMs/Baremetal machines, that have a hostname in all caps. E.g. "NUC-1"
2. Create a kubeone cluster, with a kubeone similar to this (unfortunately I don't have the exact kubeone, but it is fairly similar to this). Basically just a standard cluster with maybe one or two nodes. Issue should occur regardless of the number of nodes I think

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: lab
versions:
  kubernetes: "1.27.7"
cloudProvider:
  none: {}

controlPlane:
  hosts:
    - publicAddress: "192.168.5.42"
      privateAddress: "192.168.5.42"
      sshUsername: kubermatic
      # by setting empty taints, the controlPlane node is also being used to schedule regular workloads
      taints: []
      labels:
        location: proxmox
        pool: 5gcore

staticWorkers:
  hosts:
    - publicAddress: "192.168.5.80"
      privateAddress: "192.168.5.80"
      sshUsername: hhi
      labels:
        location: lab
        pool: 5gcore
    - publicAddress: "192.168.5.26"
      privateAddress: "192.168.5.26"
      sshUsername: fokus
      labels:
        location: lab
        pool: gnb

apiEndpoint:
  host: "192.168.5.42"
  port: 6443

machineController:
  deploy: false


```

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "7",
    "gitVersion": "1.7.0",
    "gitCommit": "1195366fd0cf11f314d194a3b29b6a782afde9a8",
    "gitTreeState": "",
    "buildDate": "2023-09-08T14:02:33Z",
    "goVersion": "go1.20.5",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "57",
    "gitVersion": "v1.57.3",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}

```

### What cloud provider are you running on?

baremetal

### What operating system are you running in your cluster?

Ubuntu 20.04
