### ISSUE TITLE
KubeOne 1.8.0 ships Calico version (3.27.2) broken on ARM64 in Canal addon

### ISSUE THREAD

**Issue by embik** [kubermatic/kubeone#3198]
### What happened?

I wanted to upgrade my homelab from KubeOne 1.7 to KubeOne 1.8. The `canal` (default) CNI addon was fine on the Raspberry Pi 5  nodes, but `canal` pods are now in CrashLoopBackOff:

```sh
$ kubectl logs canal-ztrxm -c mount-bpffs
calico-node: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
```

This appears to be https://github.com/projectcalico/calico/issues/8541, which affects ARM64 in general.

We need to update to [3.27.3](https://github.com/projectcalico/calico/blob/v3.27.3/release-notes/v3.27.3-release-notes.md), which has a fix for this.

### Expected behavior

Canal keeps working as CNI on ARM64 nodes.

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "8",
    "gitVersion": "v1.8.0",
    "gitCommit": "none",
    "gitTreeState": "",
    "buildDate": "2024-05-14T15:31:58Z",
    "goVersion": "go1.22.3",
    "compiler": "gc",
    "platform": "darwin/arm64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "59",
    "gitVersion": "v1.59.1",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

(custom 1.8.0 homebrew build from my [tap](https://github.com/embik/homebrew-tap))

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: raspi
versions:
  kubernetes: '1.27.13'
cloudProvider:
  none: {}

controlPlane:
  hosts:
    - publicAddress: '<redacted>'
      privateAddress: '<redacted>'
      sshUsername: embik
      taints: []

staticWorkers:
  hosts:
    - publicAddress: '<redacted>'
      privateAddress: '<redacted>'
      sshUsername: embik

apiEndpoint:
  host: '<redacted>'
  port: 6443

machineController:
  deploy: false
```

</details>

### What cloud provider are you running on?

Baremetal

### What operating system are you running in your cluster?

Raspberry Pi OS / Debian 12 (bookworm)
