### ISSUE TITLE
Allow prioritize user-addons / helm-releases

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#3201]
### Description of the feature you would like to add / User story

Currently we have useraddons deployed before the helm releases. But in case when CNI is set to be external and the actual CNI driver is deployed via the helmRelease, nodes will not be Ready until helm release happened.

If we simply change the order, the vise-versa problem will be true in case when CNI driver is deployed via the addon.

### Solution details

Unify the logic to deploy useraddons and helm releases. Add `weight` fields to both [Addon](https://docs.kubermatic.com/kubeone/v1.8/references/kubeone-cluster-v1beta2/#addon) and [HelmRelease](https://docs.kubermatic.com/kubeone/v1.8/references/kubeone-cluster-v1beta2/#helmrelease) types. Consider this field as a priority when deploying.

### Alternative approaches

Add new type in [KubeOneCluster](https://docs.kubermatic.com/kubeone/v1.8/references/kubeone-cluster-v1beta2/#kubeonecluster) `workloads` that will unify under one umbrella all existing and future types of deploys (addons/helmReleases). Deprecate `addons.addons` and `helmReleases`.

examples:

```yaml
addons:
  enable: true
  addons: ## this will be deprecated, yet still working for some time
  - name: default-storage-class
    weight: 100

helmReleases:  ## this will be deprecated, yet still working for some time
  - chart: kured
    repoURL: https://kubereboot.github.io/charts
    namespace: kube-system
    version: 5.4.5
    weight: 500

## this will make a unified list naturally defining the order of deployment
workloads:
  - addon:
      name: backups-restic
  - addon:
      name: unattended-upgrades
  - helmChart:
      chart: kured
      repoURL: https://kubereboot.github.io/charts
      namespace: kube-system
      version: 5.4.5
  - addon:
      name: default-storage-class
```

**Comment by kron4eg** [comment]
Closed in #3248

**Comment by xmudrii** [comment]
I don't think that we ever fixed this issue because looking at https://github.com/kubermatic/kubeone/blob/8b8d79407b2ea755572b05042c152e83255bc590/pkg/tasks/tasks.go#L279-L293, it still looks like we always first deploy addons, so you can't deploy any Helm chart before the addons.

If I'm mistaken, @kron4eg can you please provide an example of how this works in the new API version?
/reopen

**Comment by kron4eg** [comment]
> I don't think that we ever fixed this issue because looking at
> 
> [kubeone/pkg/tasks/tasks.go](https://github.com/kubermatic/kubeone/blob/8b8d79407b2ea755572b05042c152e83255bc590/pkg/tasks/tasks.go#L279-L293)
> 
> Lines 279 to 293 in [8b8d794](/kubermatic/kubeone/commit/8b8d79407b2ea755572b05042c152e83255bc590)
>  { 
>  	Fn:          addons.Ensure, 
>  	Operation:   "applying addons", 
>  	Description: "ensure embedded addons", 
>  }, 
>  { 
>  	Fn:          addons.EnsureUserAddons, 
>  	Operation:   "applying addons", 
>  	Description: "ensure custom addons", 
>  	Predicate:   func(s *state.State) bool { return s.Cluster.Addons != nil }, 
>  }, 
>  { 
>  	Fn:        localhelm.Deploy, 
>  	Operation: "releasing core helm charts", 
>  }, 
> 
> It still looks like we always first deploy addons, so you can't deploy any Helm chart before the addons.

This meant to make it easier to transition into 


```yaml
addons:
  addons:
  - helmRelease:
      chart: kube-state-metrics
      namespace: kube-state-metrics
      releaseName: ksm
      repoURL: https://prometheus-community.github.io/helm-charts
      timeout: 0s
      values:
      - valuesFile: ksm-values.yaml
      - inline:
          replicas: 3
      version: 4.22.3
  - addon:
      name: name1
```

However the v1beta2 also been used so we couldn't simply stop applying user addons from v1beta2.
