### ISSUE TITLE
Deploying user defined addons before external CCM initialization populates ca-bundle too late

### ISSUE THREAD

**Issue by sschmittsva** [kubermatic/kubeone#3238]
### What happened?

Applying addon default-storage-class gets stuck in retry:

```console
WARN[14:12:34 CEST] Retrying task...                             
INFO[14:12:35 CEST] Applying user provided addons...             
INFO[14:12:35 CEST] Applying addon default-storage-class...      
INFO[14:12:35 CEST] Parsing addons manifest 'storage-class.yaml' 
+ sudo KUBECONFIG=/etc/kubernetes/admin.conf \
kubectl apply -f - --prune -l "kubeone.io/addon=default-storage-class"

Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validation-webhook.snapshot.storage.k8s.io": failed to call webhook: Post "https://snapshot-validation-service.kube-system.svc:443/volumesnapshot?timeout=2s": dial tcp 10.111.79.249:443: connect: connection refused
storageclass.storage.k8s.io/cinder-csi unchanged
storageclass.storage.k8s.io/standard unchanged
```

### Expected behavior

addon gets installed and kubeone apply finishes.

### How to reproduce the issue?

Use kubeone starting from version 1.7.4 that includes #3068 where user defined addons before external CCM initialization. 
I need to add a private ca to the bundle because our openstack is self-signed.
With #3069, the ca-bundle is not populated prior to adding the addon default-storage-class. Events of the machine controller:

```console
│   Warning  FailedMount       97s (x6 over 13m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[ca-bundle], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition           │
│   Warning  FailedMount       47s (x15 over 15m)  kubelet            MountVolume.SetUp failed for volume "ca-bundle" : configmap "ca-bundle" not found  
```

### What KubeOne version are you using?

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "7",
    "gitVersion": "1.7.4",
    "gitCommit": "675d9c51e3e57312723d23930f42a14ce7486ae7",
    "gitTreeState": "",
    "buildDate": "2024-05-02T13:40:13Z",
    "goVersion": "go1.21.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "57",
    "gitVersion": "v1.57.6",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.27.0'
clusterNetwork:
  cni:
    canal:
      mtu: 1392
machineController:
  deploy: true
caBundle: |
  -----BEGIN CERTIFICATE-----
  ...
  -----END CERTIFICATE-----

cloudProvider:
  openstack: {}
  external: true
  cloudConfig: |
    [Global]
    auth-url=<redacted>
    application-credential-id=<redacted>
    application-credential-secret=<redacted>
    [LoadBalancer]
    subnet-id=<redacted>
addons:
  enable: true
  addons:
    - name: default-storage-class
    - name: csi-openstack-cinder
```

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your cluster?

Ubuntu 22.04
