### ISSUE TITLE
Helm Releases timeout is not working with human-readable format

### ISSUE THREAD

**Issue by mohamed-rafraf** [kubermatic/kubeone#3239]
### What happened?

Helm Releases timeout is not working with human-readable format (for example 15m30s). It supports number only

### Expected behavior

Kubeone Apply Command works 

### How to reproduce the issue?

Define a timeout for helm release inside `kubeone.yaml` file 
```yaml
helmReleases:
  - releaseName: cert-manager
    chart: ./charts/cert-manager
    namespace: cert-manager
    wait: true
    timeout: 5m30s
```
