### ISSUE TITLE
Validation permits having cloudProvider.none and machineController.deploy=true

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubeone#3366]
### What happened?
Sometimes people can be confused and try to set unsupported config combination that lead to very obscure error messages, for example in this case:
```
Task failed, error was: runtime: unmarshalling manifest "deployment-controller.yaml"
error converting YAML to JSON: yaml: line 64: could not find expected ':'
```

### Expected behavior

KubeOne should error out early, clearly indicating that such a config is not supported.

### What KubeOne version are you using?
Any of them.

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: kubeone
versions:
  kubernetes: 1.29.7

cloudProvider:
  none: {}

controlPlane:
  hosts:
    - privateAddress: 10.xxx
    - privateAddress: 10.xxx
    - privateAddress: 10.xxx

apiEndpoint:
  host: 10.xxx
  alternativeNames:
    - seed.xxx
  port: 6443

machineController:
  deploy: true
operatingSystemManager:
  deploy: true

```

</details>
