### ISSUE TITLE
Integrating KubeOVN CNI in KubeOne

### ISSUE THREAD

**Issue by mohamed-rafraf** [kubermatic/kubeone#3539]
### Description of the feature:
As a user, I would like KubeOVN CNI to be automatically installed and configured after the provisioning of a KubeOne cluster. This integration would streamline the process of leveraging the Kubermatic Cloud Stack, ensuring that the KubeOVN CNI is an integral part of the KubeOne installation process.

**Comment by kron4eg** [comment]
> KubeOVN CNI to be automatically installed

```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

...

clusterNetwork:
  cni:
    external: true

helmReleases:
  - chart: kube-ovn
    repoURL: https://kubeovn.github.io/kube-ovn/
    namespace: kube-system
    version: 0.1.0
    values:
      - valuesFile: kube-ovn.yaml   # should contain MASTER_NODES: Node0IP,Node1IP,Node2IP
```
