### ISSUE TITLE
Helm integration fails despite providing the correct repoURL and version.

### ISSUE THREAD

**Issue by rajaSahil** [kubermatic/kubeone#3576]
### What happened?
Helm integration fails despite providing the correct repoURL and version.

Chart: `cachet`
RepoURL: `https://raw.githubusercontent.com/deliveryhero/helm-charts/refs/heads/master`
Version: `1.3.5`

### Issue
When creating a cluster using KubeOne, the following Helm integration error occurs:

#### kubeone.yaml Configuration
```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.29.4'
cloudProvider:
  aws: {}
  external: true
helmReleases:
  - chart: cachet
    repoURL: https://raw.githubusercontent.com/deliveryhero/helm-charts/refs/heads/master
    namespace: cachet
    version: 1.3.5
    values:
      - valuesFile: ./values/cachet.yaml
```

#### Error Message
```
WARN[00:21:35 IST] Retrying task...                             
INFO[00:21:38 IST] Deploying helm chart cachet as release cachet 
WARN[00:21:38 IST] Task failed, error was: runtime: locating helm chart
invalid_reference: invalid tag 
```

### Expected behavior

Helm releases provided should be installed without any error.

### How to reproduce the issue?

Try installing the provided Helm release configuration using KubeOne.

### What KubeOne version are you using?

<details>

```console
$ kubeone version
# 1.9.0
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.29.4'
cloudProvider:
  aws: {}
  external: true
helmReleases:
  - chart: cachet
    repoURL: https://raw.githubusercontent.com/deliveryhero/helm-charts/refs/heads/master
    namespace: cachet
    version: 1.3.5
    values:
      - valuesFile: ./values/cachet.yaml
```

</details>

### What cloud provider are you running on?
AWS
