### ISSUE TITLE
Unable to update containerd mirrors

### ISSUE THREAD

**Issue by nilpntr** [kubermatic/kubeone#3628]
I'm trying to mirror docker.io to mirror.gcr.io following the docs. So I've added this to my KubeOne config:
```yaml
containerRuntime:
    containerd:
        registries:
            docker.io:
                mirrors:
                    - mirror.gcr.io
```
After applying the osc's(OperatingSystemConfig's) still had the default registry-1.docker.io mirror setup so I deleted all the OSC's and after reconciliation they were correct. I tried to rollout a new machine/machinedeployment but they still have the default mirror setup in /etc/containerd/config.toml:
```toml
version = 2

[metrics]
address = "127.0.0.1:1338"

[plugins]
[plugins."io.containerd.grpc.v1.cri"]
sandbox_image = "registry.k8s.io/pause:3.10"
[plugins."io.containerd.grpc.v1.cri".containerd]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
SystemdCgroup = true
[plugins."io.containerd.grpc.v1.cri".registry]
[plugins."io.containerd.grpc.v1.cri".registry.mirrors]
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
endpoint = ["https://registry-1.docker.io"]
```

Any ideas to fix this?

**Comment by nilpntr** [comment]
> [@nilpntr](https://github.com/nilpntr) did you closed the issue accidentally?

Nope, made it working. Forgot to mention that i got it working. Do you guys have any plans to support the new mirror syntax using config_path?

**Comment by tobstone** [comment]
@nilpntr  how did you get this working? i have the same problem

**Comment by nilpntr** [comment]
I've added this to the kubeone config and rolled it out:
```yaml
containerRuntime:
    containerd:
        registries:
            docker.io:
                mirrors:
                    - mirror.gcr.io
```
Then deleted the `operatingsystemconfigs.operatingsystemmanager.k8c.io` resources to make sure the containerd config is in there containing the correct mirrors. Then rollout new machine deployments/machines or run this:
`sudo sed -i 's|https://registry-1.docker.io|mirror.gcr.io|g' /etc/containerd/config.toml && systemctl restart containerd`
