### ISSUE TITLE
add configure-cloud-routes = false to aws configuration

### ISSUE THREAD

**Issue by maksim-paskal** [kubermatic/kubeone#627]
After installing aws cluster with default kubeone config

```
apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster
name: cluster-dev
versions:
  kubernetes: '1.14.5'
cloudProvider:
  name: 'aws'
```
there are many annoying messages in  kube-controller-manager pod logs

**kubectl -n kube-system logs kube-controller-manager...**
```
route_controller.go:120] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: kubernetes
```

Please add **configure-cloud-routes: "false"** as  controllerManager extraArgs config to default configuration aws cluster

```
controllerManager:
  extraArgs:
    cloud-config: /etc/kubernetes/cloud-config
    cloud-provider: aws
    configure-cloud-routes: "false"
```

**Comment by maksim-paskal** [comment]
Maybe better make new "feature" as the **extraArgs** to configure kubernetes components ?

```
apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster
name: cluster-dev
versions:
  kubernetes: '1.14.5'
cloudProvider:
  name: 'aws'
features:
  extraArgs:
    controllerManager:
    - configure-cloud-routes=false
    - node-monitor-period=2s
    - node-monitor-grace-period=16s
    - pod-eviction-timeout=30s
    kubelet:
    - node-status-update-frequency=4s
  metricsServer:
    enable: false
machineController:
  deploy: false
```


view my commit

https://github.com/maksim-paskal/kubeone/commit/db23ba89b83440101436638fa1a74a1b1fc8681e
