### ISSUE TITLE
machineController.provider field is not respected when deploying machine-controller

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#765]
**What happened**:

Setting a different provider for machine-controller using the `.machineController.provider` key doesn't seem to work at all. Even if the key is set, credentials would be deployed based on `.cloudProvider.name`.

**What is the expected behavior**:

The expected behavior is that the secret and environment variables bindings for machine-controller are created respecting `.machineController.provider`.

**How to reproduce the issue**:

The common use case is using the `none` provider, such as:

```yaml
apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster
name: demo-cluster
versions:
  kubernetes: 1.16.1
cloudProvider:
  name: none
  external: true
machineController:
  deploy: true
  provider: openstack
```

**Information about the environment**:
KubeOne version (`kubeone version`): `master`@https://github.com/kubermatic/kubeone/commit/63afc8f4752a30628cf1f6ff33e138c8fdc7c169

**Comment by mkjoerg** [comment]
This is actually making things a little bit complicated, because if you manually provide these secrets afterwards and patch the deployment of machine-controller and machine-controller-webhook, each time you upgrade, everything is overwritten. So as a workaround, you need to provide the secret and the patching manually after each upgrade.

**Comment by mkjoerg** [comment]
A quick fix for this problem is to create a secret with the following specs:

```yaml
# machine-controller-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: machine-controller-openstack
  namespace: kube-system
type: Opaque
data:
  OS_AUTH_URL: XXX
  OS_USER_NAME: XXX
  OS_PASSWORD: XXX
  OS_DOMAIN_NAME: XXX
  OS_TENANT_NAME: XXX
  OS_TENANT_ID: XXX
  OS_REGION_NAME: XXX
```
The secret can be created directly and you have to provide this only once, due to the fact that it gets not overwritten.

Additionally you need two patch files:

```yaml
# envfrom-controller-patch.yaml
spec:
  template:
    spec:
      containers:
      - name: machine-controller
        envFrom:
          - secretRef:
              name: machine-controller-openstack
```

```yaml
# envfrom-webhook-patch.yaml
spec:
  template:
    spec:
      containers:
      - name: machine-controller-webhook
        envFrom:
          - secretRef:
              name: machine-controller-openstack
```

After this you can patch the deployments by running:

```sh
kubectl -n kube-system patch deploy machine-controller --patch "$(cat envfrom-controller-patch.yaml)"
kubectl -n kube-system patch deploy machine-controller-webhook --patch "$(cat envfrom-webhook-patch.yaml)"
```

You will have to do this after every update.
