### ISSUE TITLE
machine-controller is not bound to the master node

### ISSUE THREAD

**Issue by mooperd** [kubermatic/kubeone#792]
Hi,

I have found that the machine-controller pod can get scheduled on the worker nodes if I reboot the master or something. I think this should be stuck to the control plane.

Currently I am fixing this by retrofitting the following to the deployment.

```
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      containers:
```

It would be **awesome** if I could have control over the various services that are deployed in the kube-system namespace but its all embedded in the code somewhere. 

Cheers,

Andrew
