### ISSUE TITLE
cloud-config file was not changed during cluster upgrade

### ISSUE THREAD

**Issue by erdii** [kubermatic/kubeone#833]
**What happened**:
After upgrading a GCP based k1-cluster from 1.15.5 to 1.15.11 (and later  1.16.8) via `kubeone upgrade config.yaml --tfjson tf.json` the cloud-controller could not create routes for (worker?) nodes anymore.
It always errored with: `Warning  FailedToCreateRoute      2m37s                 route_controller                                Could not create route 567b09ad-db20-46c5-aec0-8f19d6f814e3 10.244.10.0/24 for node run-2-alpha-pool1-77bc85f967-l6hpq after 218.408669ms: instance not found`
After a while of fiddling around, I found out, that the cloud-config at /etc/kubernetes/cloud-config was empty and the kubeone upgrade command (I appended `--force` to retry) did NOT copy the expected values from the cluster configuration:

```yaml
apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster
name: run-2-alpha
versions:
  kubernetes: '1.16.8'
cloudProvider:
  name: 'gce'
  cloudConfig: |
    [global]
    multizone = true
```

I manually sshed into the master-nodes, issued a

```shell
cat > /etc/kubernetes/cloud-config <<EOF
[global]
multizone = true
EOF
```

and rebootet them one-by-one, which fixed the issue.

**What is the expected behavior**: Kubeone should update the cloud-config file content based on config yaml input.

**How to reproduce the issue**: ?

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): 0.11.0
Operating system: Ubuntu 19.10
Provider you're deploying cluster on: GCP
Operating system you're deploying on: Ubuntu 18.04.3 LTS
