### ISSUE TITLE
Invalid machine deployment env

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubeone#92]
In some cases kubeone tries to create the machine deployment with broken env entries.

``` yaml
   spec:
      containers:
      - args:
        - -logtostderr
        - -v
        - "4"
        - -internal-listen-address
        - 0.0.0.0:8085
        - -cluster-dns
        - 10.96.0.10
        command:
        - /usr/local/bin/machine-controller
        env:
        - name: ""
        - name: ""
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: machine-controller-credentials
```
